spring:
  profiles.active: dev
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
logging:
  level:
    com.mycompany: DEBUG
    org.togglz: DEBUG
togglz:
  feature-enums: com.mycompany.MyFeatures
  features:
    HELLO_WORLD: true
    REVERSE_GREETING: false
