spring:
  profiles.active: dev
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
logging:
  level:
    com.mycompany: DEBUG
    org.togglz: DEBUG
togglz:
  console:
    feature-admin-authority: ROLE_ADMIN
  feature-manager-name: My Feature Manager
  features-file: classpath:/features.properties
  cache:
    enable: true
    time-to-live: 10000
