spring:
  profiles.active: dev
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
logging:
  level:
    com.mycompany: DEBUG
    org.togglz: DEBUG
togglz:
  enabled: true
  console:
    enabled: true
    path: /togglz
    feature-admin-authority: ROLE_ADMIN
  feature-manager-name: My Feature Manager
  features:
    HELLO_WORLD: true
    REVERSE_GREETING: true
    REVERSE_GREETING.strategy: username
    REVERSE_GREETING.param.users: user2, user3

---

spring:
  profiles: dev

---

spring:
  profiles: test

---

spring:
  profiles: prod
